### ISSUE TITLE
After Upgrading ZeroTierOne to 1.10.4 - ERROR getting ZT status: Error: EACCES: permission denied, open '/var/lib/zerotier-one/authtoken.secret'

### ISSUE THREAD

**Issue by jeremiah-k** [key-networks/ztncui#107]
I'm new to ZeroTier and just installed ZeroTierOne 1.10.3 and ztncui 0.8.6 (installed from deb file), installing both on my home server running Ubuntu 22.04 and using that machine as my controller.

Everything was going fine for a couple of days and then last night I saw there was an update for zerotier so I installed it.  Ever since, I'm getting a permissions error when trying to manage network in ztncui.

ERROR getting ZT status: Error: EACCES: permission denied, open '/var/lib/zerotier-one/authtoken.secret'

What's the best way to correct this problem?

**Comment by key-networks** [comment]
v0.8.12 of #ztncui is available for testing.
The DEB package is here:
https://key-networks.s3.us-west-1.amazonaws.com/deb/ztncui/1/x86_64/ztncui_0.8.12_amd64.deb

The RPM can be installed with:
`sudo dnf --enablerepo=ztncui-testing upgrade ztncui`

**Comment by jeremiah-k** [comment]
I installed it, restarted the services, and am getting the same error.

Error retrieving list of networks on this controller: Error: EACCES: permission denied, open '/var/lib/zerotier-one/authtoken.secret'

**Comment by ali-95** [comment]
у меня тоже самое 
I have the same thing

**Comment by jeremiah-k** [comment]
> 

Sure. This is the output of each.

```
jeremiah@homeserver:~$ grep ztncui /etc/passwd
ztncui:x:995:994::/opt/key-networks/ztncui:/bin/false

jeremiah@homeserver:~$ grep zerotier /etc/passwd
zerotier-one:x:996:995::/var/lib/zerotier-one:/usr/sbin/nologin

jeremiah@homeserver:~$ grep ztncui /etc/group
zerotier-one:x:995:ztncui
ztncui:x:994:

jeremiah@homeserver:~$ grep zerotier /etc/group
zerotier-one:x:995:ztncui

jeremiah@homeserver:~$ ls -l /var/lib/zerotier-one/authtoken.secret
-rw------- 1 zerotier-one zerotier-one 24 Mar  6 20:44 /var/lib/zerotier-one/authtoken.secret
```

**Comment by ali-95** [comment]
```
[root@Zerotier ~]# grep ztncui /etc/passwd
ztncui:x:996:993::/opt/key-networks/ztncui:/bin/false
[root@Zerotier ~]# grep zerotier /etc/passwd
zerotier-one:x:997:994::/var/lib/zerotier-one:/sbin/nologin
[root@Zerotier ~]# grep ztncui /etc/group
zerotier-one:x:994:ztncui
ztncui:x:993:
[root@Zerotier ~]# grep zerotier /etc/group
zerotier-one:x:994:ztncui
[root@Zerotier ~]# ls -l /var/lib/zerotier-one/authtoken.secret
-rw------- 1 zerotier-one zerotier-one 24 Feb 26 18:18 /var/lib/zerotier-one/authtoken.secret
[root@Zerotier ~]# 
```

**Comment by noodlenoggan** [comment]
I had to revert ZT to 1.10.3 then re-applied the commands below as per the ZTNCUI main page for installation:

--------------
A: Allow access to /var/lib/zerotier-one/authtoken.secret
The user running the ztncui app needs read access to authtoken.secret. This can be achieved with:

sudo usermod -aG zerotier-one username
sudo chmod g+r /var/lib/zerotier-one/authtoken.secret
Where:

username is the user running the ztncui app
Note that you need to log out and in again to apply the new group membership.
--------------

**Comment by key-networks** [comment]
Please try this one after upgrading to ZT 1.10.4:

For DEB:
https://key-networks.s3.us-west-1.amazonaws.com/deb/ztncui/1/x86_64/ztncui_0.8.13_amd64.deb

For RPM:
`sudo dnf --enablerepo=ztncui-testing upgrade ztncui`

**Comment by noodlenoggan** [comment]
On ubuntu, running the RPM command returns dnf: command not found

**Comment by noodlenoggan** [comment]
Same response as before

**Comment by key-networks** [comment]
My test on Ubuntu 22.04 worked:

```
$ dpkg -l zerotier-one ztncui
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-==================================>
ii  zerotier-one   1.10.3       amd64        ZeroTier network virtualization se>
ii  ztncui         0.8.10       amd64        ZeroTier network controller user i>

$ ls -l /var/lib/zerotier-one/authtoken.secret
-rw-r----- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret

$ sudo apt upgrade zerotier-one

$ ls -l /var/lib/zerotier-one/authtoken.secret
-rw------- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret
```
Note that the group read permission has disappeared and the error exists in the UI at this point.

Now the upgrade of ztncui:
```
$ dpkg -l zerotier-one ztncui
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-==================================>
ii  zerotier-one   1.10.4       amd64        ZeroTier network virtualization se>
ii  ztncui         0.8.10       amd64        ZeroTier network controller user i>

$ sudo dpkg -i ztncui_0.8.13_amd64.deb

$ dpkg -l zerotier-one ztncui
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-==================================>
ii  zerotier-one   1.10.4       amd64        ZeroTier network virtualization se>
ii  ztncui         0.8.13       amd64        ZeroTier network controller user i>
$ ls -l /var/lib/zerotier-one/authtoken.secret
-rw-r----- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret
```
Note the return of the group read permission after installing ztncui 0.8.13.  At this point, the problem is resolved and the UI functions correctly.

**Comment by noodlenoggan** [comment]
root@ztnc:~# dpkg -l zerotier-one ztncui
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-==================================>
ii  zerotier-one   1.10.4       amd64        ZeroTier network virtualization se>
ii  ztncui         0.8.13       amd64        ZeroTier network controller user i>


root@ztnc:~# ls -l /var/lib/zerotier-one/authtoken.secret
-rw------- 1 zerotier-one zerotier-one 24 Apr 14  2021 /var/lib/zerotier-one/authtoken.secret
root@ztnc:~#

**Comment by key-networks** [comment]
In which order did you install ztncui and zerotier-one?

**Comment by noodlenoggan** [comment]
Installed zt 1.10.4 then ztncui 0.8.13

**Comment by noodlenoggan** [comment]
This is weird. I restored the VM snapshot back to ZTNCUI web gui says I have 1.10.3 but when I ran dpkg cmd, it shows I have 1.10.4. I then ran zerotier-cli status, it shows I have 1.10.3. I'm confused why dpkg says I have 1.10.4. 

root@ztnc:~# dpkg -l zerotier-one ztncui
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-==================================>
ii  zerotier-one   1.10.4       amd64        ZeroTier network virtualization se>
ii  ztncui         0.8.6        amd64        ZeroTier network controller user i>

root@ztnc:~# zerotier-cli status
200 info XXXXXXXXX 1.10.3 ONLINE

I then tried to upgrade zerotier-one, it says it's already at the latest, 1.10.4.

root@ztnc:~# apt upgrade zerotier-one
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zerotier-one is already the newest version (1.10.4).
Calculating upgrade... Done

I'm running ubuntu 20.04.5 LTS - 64bit VM in a Win10 Host

**Comment by key-networks** [comment]
It looks like zerotier-one is now setting the permissions as it starts up.  You can prove this as follows:
```
$ ls -l /var/lib/zerotier-one/authtoken.secret
-rw------- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret
$ sudo chmod g+r /var/lib/zerotier-one/authtoken.secret
$ ls -l /var/lib/zerotier-one/authtoken.secret
-rw-r----- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret
$ sudo systemctl restart zerotier-one
$ ls -l /var/lib/zerotier-one/authtoken.secret
-rw------- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret
```

To resolve this, you have to add a ZT_TOKEN like to your ztncui .env file as follows:
```
sudo -i
echo ZT_TOKEN=`cat /var/lib/zerotier-one/authtoken.secret` >> /opt/key-networks/ztncui/.env
chmod 600 /opt/key-networks/ztncui/.env
chown ztncui.ztncui /opt/key-networks/ztncui/.env
systemctl restart ztncui
```

**Comment by noodlenoggan** [comment]
I've added the ZT_TOKEN as instructed but I can't seem to upgrade ZT from 1.10.3 to 1.10.4.   Will play more with this tomorrow. Thank you for your help!

**Comment by key-networks** [comment]
You're welcome.

**Comment by noodlenoggan** [comment]
Rebooted the VM and ZT 1.10.4 showed up. ZTNCUI is also working!

**Comment by key-networks** [comment]
Great! :+1:

**Comment by jeremiah-k** [comment]
> It looks like zerotier-one is now setting the permissions as it starts up. You can prove this as follows:
> 
> ```
> $ ls -l /var/lib/zerotier-one/authtoken.secret
> -rw------- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret
> $ sudo chmod g+r /var/lib/zerotier-one/authtoken.secret
> $ ls -l /var/lib/zerotier-one/authtoken.secret
> -rw-r----- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret
> $ sudo systemctl restart zerotier-one
> $ ls -l /var/lib/zerotier-one/authtoken.secret
> -rw------- 1 zerotier-one zerotier-one 24 Feb 25 12:40 /var/lib/zerotier-one/authtoken.secret
> ```
> 
> To resolve this, you have to add a ZT_TOKEN like to your ztncui .env file as follows:
> 
> ```
> sudo -i
> echo ZT_TOKEN=`cat /var/lib/zerotier-one/authtoken.secret` >> /opt/key-networks/ztncui/.env
> chmod 400 /opt/key-networks/ztncui/.env
> chown ztncui.ztncui /opt/key-networks/ztncui/.env
> systemctl restart ztncui
> ```

This solved the issue.  Thank you.

**Comment by efcadu** [comment]
Hello, I have the same problem after upgrading to 1.10.4
Resolved it and, but get other error on "Network" - "members" (or "details") page:
"Error resolving detail for network <network id here>: HTTPError: Response code 404 (Not Found)"
