### ISSUE TITLE
After updating to ZeroTier 1.10.4 admin panel in Chinese

### ISSUE THREAD

**Issue by opiym-7** [key-networks/ztncui#109]
How to change the language from Chinese to English?

**Comment by lideming** [comment]
There is no Chinese text in this project.
I guess you're using a modified version of ztncui.

**Comment by opiym-7** [comment]
No. I am using the official version.
Can this be checked somehow?

**Comment by key-networks** [comment]
Where did you find this official version with Chinese text?

**Comment by youtehub** [comment]
It can be used normally. It is recommended to directly install the official version instead of the one on gitee.com. The official version is pure English and has not been translated into Chinese

**Comment by key-networks** [comment]
Instructions on installing the official version are here https://key-networks.com/ztncui/
