### ISSUE TITLE
[Q] Reverse Proxy Subdirectory?

### ISSUE THREAD

**Issue by soakes** [key-networks/ztncui#11]
I am trying to proxy this through a subdirectory but its links and css/images etc are all at the wrong URLS (uses base url without sub).  Is there a flag you can give the path?  http_path=/ztncui?

**Comment by key-networks** [comment]
Looking into this... it's not as simple as appears at first sight.

**Comment by soakes** [comment]
Thanks very much for taking a look at it.  I kind of figured the same.  For now, I have a workaround using an older version and has been pinned.  However, whats annoying is ZT has removed the old version from their site so you no longer can grab it directly from there.  Thankfully it's just a single binary which is needed, so it's easy to replace if needed.

**Comment by key-networks** [comment]
Did you manage to sort this out with some rewrite rules?  If so, would you mind sharing them?

**Comment by itskenny0** [comment]
I’m fairly sure one could do this with the Caddy webserver and it’s proxy directive. It allows to proxy into a subdirectory without passing it to the backend using the ‘without’ argument. I could probably write an example config for this, but I’m on holiday this week.

Here’s the docs if someone wants to have a crack at it:
https://caddyserver.com/docs/proxy
