### ISSUE TITLE
[BUG] ZTNCUI breaks if you upgrade zerotier

### ISSUE THREAD

**Issue by soakes** [key-networks/ztncui#12]
**OS:** CentOS 7
**Installed ZT version:** zerotier-one-1.2.4-1.el7.centos.x86_64
**Upgraded ZT version:** zerotier-one-1.2.8-1.el7.centos.x86_64

If you upgrade zerotier, it totally breaks ZTNCUI.  The error is this...

`Error resolving detail for network e5*****: ParseError: Unexpected token c in JSON at position 3 in "http://localhost:9993/controller/network/e5*******/member": {""c71****":1,""c4df****":2,""e0****":3,""64d***":0,""6bf***...`

I have tested this several times and happens every time.

They must of changed something in the API but what, I don't know.  A workaround is to use the working version as listed above and not to upgrade.

**Comment by key-networks** [comment]
Thanks for your feedback.  This issue has been reported before: https://github.com/key-networks/ztncui/issues/6

It's a bug in Zerotier 1.2.8 - in the meantime, just stick to 1.2.4 .

**Comment by key-networks** [comment]
You can get old Zerotier releases here:
https://download.zerotier.com/RELEASES/

**Comment by soakes** [comment]
Thank you very much.  Totally missed that.

**Comment by key-networks** [comment]
A new Docker image is available at https://hub.docker.com/r/keynetworks/ztncui that incorporates zerotier-one-1.2.12 and ztncui-0.5.4.

**Comment by soakes** [comment]
Really awesome, thank you.
