### ISSUE TITLE
Imcompatible with zerotier 1.12.1

### ISSUE THREAD

**Issue by GreatMichaelLee** [key-networks/ztncui#123]
I am using the latest ztncui 0.8.13 and latest zerotier 1.12.1 seems the ztncui now is imcompatble with the change of zerotier 1.12.1 in some places, the path of 'networks ->network name->details' page cannot show details(it prompts the 404 http error when poll one particular network Id) and only can listed the network name in networks tab, so the futher configuration is impossible, can anyone help to fix this?

thanks.

**Comment by Ilmereth** [comment]
Same Problem here. It started with the upgrade to 1.12.0 and still persists. The Network is still working, but the GUI throws up the following error when opening the `Details` and `Members` submenu on the Networks Page:
Error resolving detail for network xxx: HTTPError: Response code 404 (Not Found).

**Comment by GreatMichaelLee** [comment]
> Same Problem here. I am using ztncui 0.8.13 as well and until the upgrade to zerotier-one 1.12.0 everything worked like a charm. After the Upgrade to 1.12.0 and later to 1.12.1 the GUI throws up the following error when opening the `Details` and `Members` submenu on the Networks Page: Error resolving detail for network xxx: HTTPError: Response code 404 (Not Found). The Network is still working, and all the clients are able to connect fine.

I just guess zerotier has changed part of their configuration database structure or their access API interfaces , and this cause the issue, ztncui cannot parse the data from the http API, hope the author could fix it ASAP, the ztncui is great for me.

**Comment by churchmice** [comment]
Same issue here.
I tried to create a new network, everything is fine until I tried to join in the network and it reports 404 error

**Comment by Koromix** [comment]
Made a fork with a temporary fix: https://github.com/Koromix/ztncui

**Comment by GreatMichaelLee** [comment]
> Made a fork with a temporary fix: https://github.com/Koromix/ztncui

Can you share the bianary file or tell how to build? thanks

**Comment by efcadu** [comment]
Same issue. Downgraded zerotier-one to 1.10.3

**Comment by key-networks** [comment]
> Made a fork with a temporary fix: https://github.com/Koromix/ztncui

@Koromix thanks for your fix.  I have made a branch issue#123 including your fix.

Everyone please test on the latest and older versions of ZT.

For Debian/Ubuntu:
https://key-networks.s3.us-west-1.amazonaws.com/deb/ztncui/1/x86_64/ztncui_0.8.14_amd64.deb

For Redhat:
`sudo dnf --enablerepo=ztncui-testing upgrade ztncui`

**Comment by Ilmereth** [comment]
The fix seems to be working with 1.12.1. No Errors and working configuration/add and remove of members.
Thanks for this fast fix @Koromix @key-networks

**Comment by GreatMichaelLee** [comment]
> https://key-networks.s3.us-west-1.amazonaws.com/deb/ztncui/1/x86_64/ztncui_0.8.14_amd64.deb

I have tested on 1.12.1, seems good, thanks for the fast response.

**Comment by AndyDavis8** [comment]
Same issue here. 
After updated to ztncui_0.8.14_amd64.deb in my docker container running ZT 1.12.1, It works fine!  Thanks.
I also tried this fix on ZeroTier version 1.10.6 in previous docker container, It works fine too.
Please merge it into the master brunch.  @key-networks Thanks.

**Comment by key-networks** [comment]
This fix has been merged into master and the RPM release repo has been updated with 0.8.14, so to upgrade, please use the following instructions:

**For DEB**, download and install from:
https://key-networks.s3.us-west-1.amazonaws.com/deb/ztncui/1/x86_64/ztncui_0.8.14_amd64.deb

**For RPM**:
`sudo dnf upgrade ztncui`

Once again, thanks to @Koromix for the fix!

**Comment by ingramcomputers** [comment]
Thank you
