### ISSUE TITLE
Upgrade process?

### ISSUE THREAD

**Issue by n9yty** [key-networks/ztncui#128]
I tried to upgrade the zerotier image to 1.12.1, and the controller said I had no hosts on the network. reverting to 1.10.0 worked.

What is the upgrade process?  I simply change the version for zerotier in the docker-compose.yml file, is there something else required?

**Comment by Pietro395** [comment]
Also update the ztncui package, you can follow the instructions [here](https://key-networks.com/ztncui/), if you used the DEB just issue these commands:

`curl -O https://s3-us-west-1.amazonaws.com/key-networks/deb/ztncui/1/x86_64/ztncui_0.8.14_amd64.deb`

`sudo apt install ./ztncui_0.8.14_amd64.deb`

**Comment by n9yty** [comment]
I am using Docker containers. I will have a look. Thanks.

**Comment by n9yty** [comment]
I pulled all new docker images and now it seems it is up and running on the latest versions. Strange, as that is what I had done before, but maybe something was fixed in the interim.
