### ISSUE TITLE
Move controller to another server

### ISSUE THREAD

**Issue by saifulmr** [key-networks/ztncui#13]
Hi,
I am testing ztncui in a small development environment. 

I have currently ztncui running from docker. It has only port 3443 exposed and works fine as expected. 

Lets say our ztncui is runnning on Server1 on https://aaa.aaa.aaa.aaa:3443

Now I am testing to copy the same docker image to another server. Please know my image already have some networks and clients created, and they can communicate between each other. 

Server 2. Copied docker image is running on https://bbb.bbb.bbb.bbb:3443

If I take server1 down, and try to create a join a new client, I don't see the request coming to server2.

How can I make the server2 to act as the same network controller as server1.

Thanks & Best Regards,
Saiful Alam

**Comment by sunfic** [comment]
just did this a few days ago. 
Basically you don't need to move ztncui configuration. but if you want to, they are in /opt/key-networks
what you really want to move is zerotierOne setup. they are under /var/lib/zerotier-one/

1. setup new server with same version zerotierOne installed. 
2. one both servers, stop zerotierone services
3. copy zerotierone configuration files from old computer to new computer, setup file ownership/permission the same as old computer if needed. 
4. start zerotierone service on new server
5. install ztncui. newest version preferred. 
6. setup ztncui (https access), visit ztncui webpage use default username/password and change that. Then everything should work the same as before.

**Comment by key-networks** [comment]
@saifulmr please accept my apologies for taking so long to address this request.

To copy from one docker host to another, it is best to use volumes - please see https://github.com/key-networks/ztncui-containerized#persist-data-in-volumes on how to do this.

Then, to copy volumes from one host to another, first stop the docker container on host aaa.

Then copy the volumes across from aaa to bbb by executing this on aaa:
`docker run --rm -v ztncui:/from alpine ash -c "cd /from ; tar -cf - . " | ssh user@bbb.bbb.bbb.bbb 'docker run --rm -i -v ztncui:/to alpine ash -c "cd /to ; tar -xpvf - " '`
and:
`docker run --rm -v zt1:/from alpine ash -c "cd /from ; tar -cf - . " | ssh user@bbb.bbb.bbb.bbb 'docker run --rm -i -v zt1:/to alpine ash -c "cd /to ; tar -xpvf - " '`

Points to note:
- user@bbb.bbb.bbb.bbb must have docker admin privileges (must be part of the docker group) on host bbb.bbb.bbb.bbb.
- If you have not used the alpine image on host bbb.bbb.bbb.bbb before, you may need to run something like this on bbb.bbb.bbb.bbb before executing the copy commands above:
`docker run --rm alpine`
- Credit for the docker volume copy command goes to https://www.guidodiepen.nl/2016/05/transfer-docker-data-volume-to-another-host/

Please let me know if this works for you.

Thanks
Steve
