### ISSUE TITLE
set password from command line?

### ISSUE THREAD

**Issue by oriolrius** [key-networks/ztncui#14]
Hi, as far as I understand there is no easy way of setting the password to default.password from command line. Please, could you tell me which is the algorithm for generating a new password from CLI and avoid the setup security issue described in your documentation?

Thank you very much, regards.

Oriol

**Comment by key-networks** [comment]
Hi Oriol, the quick answer is argon2 (Argon2i).  You can probably use this https://www.npmjs.com/package/argon2-cli from the command line.  I have not tried it, but it should work to generate the password hash.  You then just need to construct the JSON around it as per the example in default.passwd .

Regards,
Steve

**Comment by oriolrius** [comment]
Thank very much Steve, it's working OK for me this workaround.
