### ISSUE TITLE
Deleting members

### ISSUE THREAD

**Issue by Fastidious** [key-networks/ztncui#16]
I deleted a member, yet the entry doesn't get removed from the list. Is there a workaround for that? The member was an old iPhone, which was surplussed without leaving the network before hand.

**Comment by key-networks** [comment]
I've noticed this as well.  It seems to be a ZeroTier issue.  The solution is to get the member to leave the network.

**Comment by Fastidious** [comment]
I went to zerotier-one directory (`/var/lig/zerotier-one/`) and was able to edit `.json`s and delete a file with the "zombie" ID in it, managing to get it removed from the list, without breaking anything.

The solution provided isn't longer possible, as I do not have the device. Is there a way to force a "defunct" member to leave a network?

**Comment by Sevenlive** [comment]
I have the same Issue....

Didn't try deleting the files yet, but i guess it will help

**Comment by key-networks** [comment]
Here is a workaround:

NETWORK=c741fda1ece47103
MEMBER=2c26433123
sudo rm /var/lib/zerotier-one/controller.d/network/${NETWORK}/member/${MEMBER}.json
sudo systemctl restart zerotier-one

**Comment by fastcat** [comment]
For others that come along and find this, I found I had to delete `/var/lib/zerotier-one/peers.d/${MEMBER}.peer` as well

**Comment by key-networks** [comment]
Thanks @fastcat

**Comment by mdPlusPlus** [comment]
Do you have the intention to add this to ztncui?

**Comment by key-networks** [comment]
@mdPlusPlus - I'm happy to accept code contributions.
