### ISSUE TITLE
Feature Request -- Editing of rules has not been implemented.

### ISSUE THREAD

**Issue by saket424** [key-networks/ztncui#19]
Would it be possible to implement this in the ztncui application ?

**Comment by key-networks** [comment]
Unfortunately I don't have the bandwidth now to do the work, but am happy to accept code contributions.

Regards
Steve

**Comment by key-networks** [comment]
A user asked for help a little while ago in applying rules.  I wrote the following bash script to help him apply the rules - perhaps you could modify it for your use:

https://gist.github.com/key-networks/c825f6b40189cb2f10a2f824e1dbf863
