### ISSUE TITLE
Unable to write ipAssignments

### ISSUE THREAD

**Issue by hijak** [key-networks/ztncui#2]
Hi

When trying to assign an IP to a node i am blocked by 

> Editing of ipAssignments has not been implemented

I can do this no problem with zerotiers API the documentation says this field should be writable too

https://github.com/zerotier/ZeroTierOne/tree/master/controller

ps. great product

Thanks

**Comment by key-networks** [comment]
I will check it out.  Are you using IPv4 or IPv6 on the virtual network?

**Comment by hijak** [comment]
thanks, Im using IPv4

**Comment by key-networks** [comment]
Jack,

Could you try the "dev" branch and let me know if it's heading in the right direction?  There are no guard rails at this stage, so it will let you assign any valid IPv4 or IPv6 address.

Thanks
Steve

**Comment by key-networks** [comment]
P.S. What I mean by no guard rails is that it currently does not check if the IP assignment falls within a managed route.  Ideally, this check needs to be added.

**Comment by key-networks** [comment]
Were you using one of the Linux packages (RPM or DEB), or the Docker image or were you working from source code?

**Comment by hijak** [comment]
Hi

Thanks for looking into this. I was trying to source somewhere to test as
im using the rpm install

**Comment by key-networks** [comment]
Ok, I haven't re-built the RPM yet.  You can only test the dev branch from source.  I'm currently looking at putting guard rails in to prevent assigning IPs that don't have a managed route.  Once I've got that right, I'll rebuild the packages and you can test.

Will keep you updated here.

**Comment by key-networks** [comment]
Jack,

Could you please test as follows:
sudo yum --enablerepo=ztncui-testing install ztncui -y

You should end up with ztncui-0.4.0-1.x86_64.

Please give me your feedback.
Thanks
Steve

**Comment by key-networks** [comment]
@hijak - have you managed to try it out?  Do you need any assistance?

**Comment by hijak** [comment]
Hi Sorry

I am going to give this ago on the weekend

**Comment by key-networks** [comment]
Try the latest release with:

sudo yum install ztncui -y

You should end up with ztncui-0.4.1-1.x86_64.

**Comment by key-networks** [comment]
@hijak did you manage to try out 0.4.1?

**Comment by hijak** [comment]
hey 

yes i have just tried the new release and it does exactly what i need it to do. I will have to test the api function but at the moment it seems perfect 

thanks
