### ISSUE TITLE
HTTP mode

### ISSUE THREAD

**Issue by makarov-roman** [key-networks/ztncui#23]
Hi, 
version: 537a567e29da8ccc83a473b327674b149b5a6419
npm start causing 
Error: ENOENT: no such file or directory, open 'etc/tls/fullchain.pem'
can I somehow to start without having cert?

Thanks

**Comment by key-networks** [comment]
Unfortunately not the way the code exists currently.  The easiest workaround is to execute this in the src directory:
`openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout etc/tls/privkey.pem -out etc/tls/fullchain.pem`

**Comment by makarov-roman** [comment]
I see. I'm perfectly okay with this . Thanks for the response.
