### ISSUE TITLE
Easy Setup deletes secondary managed routes

### ISSUE THREAD

**Issue by pjv** [key-networks/ztncui#25]
If you create a managed route (for a new subnet) on an existing ZT network, and then subsequently run easy setup on that network - for example, to change the range of the IP assignment pool for the primary ZT subnet - it then silently deletes the secondary managed route.

**Comment by key-networks** [comment]
"easy setup" is intended for simple setup of a new network that has no prior configuration.  In your case, it would be better to run "easy setup" before adding the managed route.

**Comment by pjv** [comment]
Of course I did run "easy setup" before adding the managed route. But then I subsequently wanted to make a change to the range of addresses in the IP assignment pool. Is there another easy or non-easy way to do that without running "easy setup" that will not delete the managed routes?

**Comment by key-networks** [comment]
Ah, fair enough.  You can manipulate the configuration by following the detail link for the network and then following the ipAssignmentPools link.

**Comment by pjv** [comment]
Excellent - thank you!
