### ISSUE TITLE
Perms?

### ISSUE THREAD

**Issue by justinglock40** [key-networks/ztncui#26]
What permissions are needed when running in docker? 775 for user gives write access error. and setting to 777 gives SSL cert error. 

Running the basic docker command it comes up fine?

**Comment by key-networks** [comment]
At what point do you get this error?

Have you had a look at https://github.com/key-networks/ztncui-containerized ?

**Comment by justinglock40** [comment]
Yes I have. I set the volume to this --volume ztncui:/opt/key-networks/ztncui/etc/

But when the actually container is trying to boot it gives the error mkdir permissions could not create `/opt/key-networks/ztncui/etc/storage`

However, If I chmod that directory to 777. It makes it further into the install to at which point its looks for a SSL cert in the container. Should the container make its own SSL cert or does one need to be made and provided to the container?

**Comment by justinglock40** [comment]
What permissions should it be run with. My default is with the 1000:1000 user and 775 for file/directory

**Comment by key-networks** [comment]
I forget the details and it would take some time for me to check out how I did it.  I suggest that you clone  https://github.com/key-networks/ztncui-containerized and use that as the basis for what you are trying to do.

**Comment by justinglock40** [comment]
Got it figured out

**Comment by axemann** [comment]
Hi @justinglock40,

What did you end up having to do to remedy the issue?  I'm running into the same thing using separate bind mounts for the zt1 and ztncui data, and I tried setting the ztncui directory to the same owner as zt1 (999:998), but that had no effect.

TIA

**Comment by justinglock40** [comment]
- hosts: localhost
  gather_facts: false
  tasks:
    - name: 'Set Known Facts'
      set_fact:
        role: 'zerotier-one'
        image: 'zyclonite/zerotier'
    - name: 'Including cron job'
      include_tasks: './basefiles/tasks/core.yml'

    - name: 'Setting {{role}} Volumes'
      set_fact:
        role_volumes:
          - '/opt/appdata/{{role}}/var:/var/lib/zerotier-one'
          - '/etc/localtime:/etc/localtime:ro'
    - name: 'Setting {{role}} ENV'
      set_fact:
        role_env:
          PUID: '1000'
          PGID: '1000'
          HTTP_ALL_INTERFACES: 'XXX'
    - name: 'Deploying Container for {{role}}'
      docker_container:
        name: '{{role}}'
        image: '{{image}}'
        pull: yes
        volumes: '{{role_volumes}}'
        env: '{{role_env}}'
        restart_policy: always
        devices:
          - '/dev/net/tun:/dev/net/tun'
        capabilities:
          - NET_ADMIN
        network_mode: host
        state: started
