### ISSUE TITLE
Feature request -- network controller with built-in moon

### ISSUE THREAD

**Issue by gzz2000** [key-networks/ztncui#28]
I have very little understanding of zerotier network structure, and in my understanding a network controller should announce the zerotier planet about the existence of the new network id, and listen to the planet for forwarded join request from clients, making the controller unnecessarilly dependent on the planet. It will be convenient if we can control which planet node to use, namely we may switch to a self-hosted moon for network creation that is only locally available.

I also have very little understanding of how moons works, will they and how they exchange network id information with the planet. But it was said in zerotier's webpage that it's possible to set up zerotier network in an air-gapped environment, so I think it's possible to connect our network controller to its own moon, with the moon air-gapped and store network information locally.

**Comment by Fastidious** [comment]
With the upcoming ZeroTier 2 many things will change. I am not sure if @key-networks will have the resources to update `ztncui` to accommodate for the changes, but what you are asking I am sure will break on the upcoming release of ZeroTier.

**Comment by key-networks** [comment]
@gzz2000 I agree with @Fastidious that the upcoming ZeroTier 2 will change many things.  You can find out more about that here: https://www.zerotier.com/zerotier-2-0-status/

For information on setting up your own moon, please refer to https://www.zerotier.com/manual/#4_4
