### ISSUE TITLE
zerotier-one 

### ISSUE THREAD

**Issue by synetalsolutions** [key-networks/ztncui#31]
Why we need to install zerotier-one as this source is used to create self setup so what is the dependency here.

Install zerotier-one as per instructions here: zerotier.com/download.shtml.

`curl -O https://s3-us-west-1.amazonaws.com/key-networks/deb/ztncui/1/x86_64/ztncui_0.5.8_amd64.deb
sudo apt-get install ./ztncui_0.5.8_amd64.deb`

I am trying to setup it on my own server so what further things I can use to overcome this.

Thanks

**Comment by key-networks** [comment]
Not sure if I understand your question fully, but ztncui is just a web UI for zerotier-one.  You need to install both.

**Comment by synetalsolutions** [comment]
But  zerotier-one is the client so when we setup zerotier central on our server is this compulsory to use  zerotier-one?

**Comment by key-networks** [comment]
I think that you might be confusing a few things:

- Zerotier-one is the software from Zerotier Inc that is used for end nodes to connect to a virtual network.  It is also used for setting up a standalone network controller.
- Zerotier Central is the web portal provided by Zerotier Inc here https://my.zerotier.com to allow you to use Zerotier Inc network controllers along with their web UI.
- ztncui is a web UI from Key Networks to provide an easy way to interface with your own standalone network controller.
