### ISSUE TITLE
how to expose 9993 port to acces from outside?

### ISSUE THREAD

**Issue by connected201** [key-networks/ztncui#32]
i try to write in .env ZT_ADDR=0.0.0.0:9995
but not working, other parameters like HTTP_PORT=3456 or HTTPS_PORT=3443 work well.
![Screenshot_20200429_000743](https://user-images.githubusercontent.com/20506433/80538013-a7748400-89ad-11ea-9d35-64275a2dcf63.png)
i cannot acces it from outside, because port not accept requests from outside, only from container

**Comment by key-networks** [comment]
IIRC, ZT_ADDR is to match any change you make to the port that zerotier-one is running on, i.e. you would have to change the configuration of zerotier-one to use that port.  Also, the local address (127.0.0.1) is what you would typically specify, not 0.0.0.0 .

**Comment by connected201** [comment]
how i can configure zerotier-one to accept connections from outside? where is the configuration file that i can make changes?

**Comment by key-networks** [comment]
Are you using https://github.com/key-networks/ztncui-containerized ?

**Comment by flantel** [comment]
@connected201 I think you need to run the container using HOST networking, so that zt listens on 9993 on the actual host interface, not just the container's pseudo interface.

**Comment by connected201** [comment]
i resolved my case, best regards

**Comment by Fastidious** [comment]
@connected201 while glad you resolved your case, not explaining or providing details on what was done to correct it (even if it was user's error)--which could be very important to help others with a similar problem--is wrong.

Could you please let us know how you resolved your case? Thank you.

**Comment by connected201** [comment]
https://github.com/key-networks/ztncui-containerized/issues/13
