### ISSUE TITLE
Member Status

### ISSUE THREAD

**Issue by umardraz** [key-networks/ztncui#34]
Hello!
Is there any way to get status of network's members, means how we can know a member is online or offline ?

**Comment by key-networks** [comment]
I believe that it is possible via the Zerotier API.  This is something you could do with `zerotier-cli -j status`.  To do it via ztncui would require further development work.

**Comment by pete1019** [comment]
Online Status would be so great!
Any news on this?
Thank you

**Comment by umekzg** [comment]
Last seen.
That's a big feature which wold be wonderful to have!

**Comment by Busch** [comment]
In addition to the online status, it would also be great to see if the node is relaying or connected to the controller.

**Comment by ali-95** [comment]
Можно закрывать

**Comment by key-networks** [comment]
Now in ztncui v0.7.0

**Comment by pete1019** [comment]
@key-networks awesome, thanks. What about the "last seen" feature?

**Comment by key-networks** [comment]
@pete1019 - sorry, no 'last seen', just online status.

**Comment by tremustools** [comment]
> @pete1019 - sorry, no 'last seen', just online status.

Maybe yes? last seen very good feature. Please :) Or maybe you can say how we can realize it?
