### ISSUE TITLE
Is there a reason for the discrepancy between version numbers of .rpm vs .deb packages?

### ISSUE THREAD

**Issue by mdPlusPlus** [key-networks/ztncui#35]
From: https://key-networks.com/ztncui/#installation

`https://download.key-networks.com/el7/ztncui/1/ztncui-release-1-1.noarch.rpm`  
`https://s3-us-west-1.amazonaws.com/key-networks/deb/ztncui/1/x86_64/ztncui_0.5.8_amd64.deb`

Are they both up-to-date with the current master commit?

**Comment by key-networks** [comment]
ztncui-release-1-1.noarch.rpm is to set up key-networks.repo in /etc/yum.repos.d

When you yum/dnf install ztncui it will currently install ztncui-0.5.8-1.x86_64.rpm

IIRC, they are both in line with the current master.
