### ISSUE TITLE
certbot webroot cannot find public folder

### ISSUE THREAD

**Issue by penguinthingie** [key-networks/ztncui#37]
Hello,

This project looks great and i am looking to try it out, coming across an issue with generating a certificate with certbot. I am running the .deb install which install an executable onto /opt/key-networks/ztncui, i don't see any folders there called public that certbot could attempt to create a temporary file to complete the verification process. Am i missing something?

Thanks for your help!

**Comment by key-networks** [comment]
Unfortunately the instructions at https://github.com/key-networks/ztncui are for using the source code, not the .deb or .rpm packages.  You could try using certbot in standalone or manual modes to generate the certificate and then copy the private key and certificate to /opt/key-networks/ztncui/etc/tls, overwriting privkey.pem and fullchain.pem, respectively.

**Comment by penguinthingie** [comment]
Understood. Any chance to allow customization on the UI portion with the .deb or .rpm version?

**Comment by key-networks** [comment]
It's all compiled into a package with pkg, so no easy way with the packaged version.  You could try from source, though.
