### ISSUE TITLE
arm64 deb 

### ISSUE THREAD

**Issue by guizmoau** [key-networks/ztncui#40]
Hello,

I want to install ztncui on an arm64 server.
Where can I find or how can I do to find the corresponding .deb package or manually install ?

Thanks.

**Comment by key-networks** [comment]
Sorry, there is no package for arm64.

**Comment by guizmoau** [comment]
can I install manually or compile it manually maybe ?

**Comment by key-networks** [comment]
You could try run from source... let us know the results of your endeavours.

**Comment by guizmoau** [comment]
how can I do that ?

**Comment by key-networks** [comment]
You would have to try piece together the steps from here https://github.com/key-networks/ztncui

**Comment by guizmoau** [comment]
ok

**Comment by key-networks** [comment]
You might also get some clues from here https://gist.github.com/mdPlusPlus/0f6285c6402aa4aff4aa4a9e5dfc38c0

**Comment by key-networks** [comment]
If you have issues with node 12, try node 8 which was what this was originally developed for.

**Comment by key-networks** [comment]
Also, you might want to use the branch called issue36 since this has updates to the packages file:
https://github.com/key-networks/ztncui/tree/issue%2336

**Comment by guizmoau** [comment]
ok it did works by following the steps in https://github.com/key-networks/ztncui

I did summarize all of the commands I used for the record below : 
-installed zero tier one already done

install node
sudo apt install npm
sudo npm install -g node-gyp

#sudo npm install -g argon2
#failed

sudo apt install argon2 git
git clone https://github.com/key-networks/ztncui
cd ztncui/src
npm install

sudo usermod -aG zerotier-one username
sudo chmod g+r /var/lib/zerotier-one/authtoken.secret
cp -v etc/default.passwd etc/passwd

sudo apt install certbot python-certbot-apache

#sudo certbot --apache -d yourdomain.com
#failed

cd etc/tls
openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privkey.pem -out fullchain.pem

nano .env
#add those two lines
HTTP_ALL_INTERFACES=yes
HTTPS_PORT=3443

npm start
if success to install permanent
sudo npm install -g pm2
pm2 start bin/www --name ztncui
pm2 startup
pm2 save

**Comment by key-networks** [comment]
Well done, @guizmoau !  Thanks for your feedback!

**Comment by guizmoau** [comment]
The last part below doesn't work and after reboot it doesnt load

sudo npm install -g pm2
pm2 start bin/www --name ztncui
pm2 startup
pm2 save

I am not sure how to do...ayone ?

**Comment by guizmoau** [comment]
also the certbot part failed for me because of my network configuration (NAT ports not open) and I am using a reverse proxy with caddy anyway....but it will works if you have the correct ports 80 and 443 open and accessible for the challenge response.

**Comment by guizmoau** [comment]
also the dependency argon2 required is a deb package right, not a npm ?

**Comment by guizmoau** [comment]
> The last part below doesn't work and after reboot it doesnt load
> 
> sudo npm install -g pm2
> pm2 start bin/www --name ztncui
> pm2 startup
> pm2 save
> 
> I am not sure how to do...ayone ?

I got it right when I pass the command pm2 startup it gives me a command to execute :

[PM2] To setup the Startup Script, copy/paste the following command:
sudo env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u user --hp /home/user

I did and pm2 save and reboot and it started with the server....!!

👍

**Comment by key-networks** [comment]
👍
