### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by schmerold** [key-networks/ztncui#43]
How do I backup and restore ztncui?

If I rsync ServerA:/opt/key-networks/ztncui ServerB:/opt/key-networks/ztncui

Does this create a live backup on ServerB?

**Comment by flantel** [comment]
On Sun 25 Oct 2020, 01:14 schmerold, <notifications@github.com> wrote:

> How do I backup and restore ztncui?
>
> If I rsync ServerA:/opt/key-networks/ztncui
> ServerB:/opt/key-networks/ztncui
>
> Does this create a live backup on ServerB?
>

That's would back up the GUI only. You would also need /var/lib/zerotier/
and ServerB would need zerotier itself installed.

/var/lib/zerotier is where the important stuff is.

**Comment by key-networks** [comment]
You can get some clues here:
https://github.com/key-networks/ztncui-containerized#copy-volumes-to-another-docker-host

**Comment by schmerold** [comment]
My controller used /var/lib/zerotier-one instead of /var/lib/zerotier

Thank you so much for your help.
