### ISSUE TITLE
[Question] Safe to upgrade to Zerotier 1.6?

### ISSUE THREAD

**Issue by Fastidious** [key-networks/ztncui#45]
Hi there! Before I jump the trigger, is it safe to upgrade to Zerotier 1.6? Any known issues that will cause `ztncui` to break? Thanks!

**Comment by key-networks** [comment]
Hello @Fastidious!  I haven't tried it.  If you are willing to do some testing, I suggest setting up test instance in a separate environment with a test ZT network and some test members.  Check that it all works as expected after upgrading.  It would be great if you could feed back the results here.

**Comment by Fastidious** [comment]
👌🏻 @key-networks I will spin a Lightsail instance tomorrow, test it, and report back.

**Comment by Fastidious** [comment]
@key-networks, ztncui works perfectly with 1.6.0 🎆. There are new goodies coming with 1.6.0, I wish and hope ztncui takes advantage of them!

**Comment by key-networks** [comment]
Thanks for testing, @Fastidious!
