### ISSUE TITLE
Backup network controller

### ISSUE THREAD

**Issue by Jarusss** [key-networks/ztncui#46]
Hi,
is there any way to backup my Network Controller in some way? I found that there are some files containing members details, but is there a way to backup whole network? Will try that, but - if I will do disk image backup and deploy it after damage will I still have access to administrate my network? 
Is there a way to manage my network on two Network Controllers (separate machines)?

**Comment by key-networks** [comment]
Hi @Jarusss  - you might get some clues here: https://github.com/key-networks/ztncui-containerized#copy-volumes-to-another-docker-host

**Comment by Jarusss** [comment]
hm... I will try, but:
In one of previous issues you wrote, that ztncui is designed for x86 architecture. The problem is that (if Raspberry Pi 4 is powerful machine) I tried to run it on RPi4 with success. Just wondering if there is any way to backup and/or administrate my network from two separate machine (if one of them will be unavailable or something).

**Comment by key-networks** [comment]
The rpm and deb packages will only work on x86_64, but if you are running it from source, you should be able to run it on other architectures.  The clues above should help you to find what data needs replicating.
