### ISSUE TITLE
ZeroTier 1.6.0+ DNS Configuration

### ISSUE THREAD

**Issue by lflare** [key-networks/ztncui#47]
Hello,

In the recent changes in ZeroTier, it is now possible to specify the DNS servers for a controller configuration, can that functionality be ported to ztncui as well?

**Comment by key-networks** [comment]
I'll keep that in mind if I have time to do further development.  In the meantime, code contributions are very welcome.

**Comment by GabrieleV** [comment]
Someone could post the manual configuration needed to achieve DNS functionality ?

Thx

**Comment by key-networks** [comment]
Does anyone know where the configuration of DNS is documented?  I don't see it at https://github.com/zerotier/ZeroTierOne/tree/master/controller

**Comment by key-networks** [comment]
I'm guessing that it's just a list of IP addresses... but not sure.

**Comment by lflare** [comment]
> Does anyone know where the configuration of DNS is documented? I don't see it at https://github.com/zerotier/ZeroTierOne/tree/master/controller

I just have manual configuration.

`curl -v --header "X-ZT1-Auth: $(cat /var/lib/zerotier-one/authtoken.secret)" http://localhost:9993/controller/network/NETWORKID--data '{"dns": {"domain": "INTERNAL.NET", "servers": ["DNS SERVER"]}}'`

**Comment by key-networks** [comment]
Thanks, @lflare!

**Comment by GabrieleV** [comment]
So there are only parameters that points to an existng DNS server ?
Isn't there an internal DNS server if I understood correctly ? Do we need an external DNS that syncs with hostnames like https://github.com/mje-nz/zerotier-dns ?

**Comment by Overbryd** [comment]
I configured it at my.zerotier.com and checked the JSON response from the web inspector.

There the dns sections looks like this:

```json
"dns": {
  "domain": "vlan.overbryd.com",
  "servers": [
    "8.8.8.8"
  ]
}
```

**Comment by Overbryd** [comment]
@key-networks do you have a JSON-schema somewhere of the complete zero tier configuration?

I would love to contribute to the project, but with limited information on a brittle JSON configuration (zerotier config will not work if JSON is incorrect), it seems rather hard to do. Happy to help the cause.

**Comment by key-networks** [comment]
@Overbryd unfortunately not.  IIRC, I just referred to the README.md here: https://github.com/zerotier/ZeroTierOne/tree/master/controller

**Comment by lideming** [comment]
I just created a PR (#57) which includes support for DNS configuration.

**Comment by key-networks** [comment]
Thanks, @lideming - I'll have a look at it.

**Comment by key-networks** [comment]
Does anyone want to help test https://github.com/key-networks/ztncui/pull/57 and give their feedback?  I'm having trouble building  rpm and deb packages for testing due to issues with pkg, but you can try from source in the meantime.

**Comment by ali-95** [comment]
Можно уже закрывать
