### ISSUE TITLE
ZT-TOKEN

### ISSUE THREAD

**Issue by Jarusss** [key-networks/ztncui#49]
Hi,
I have extremely naive question ;) During the installation steps you wrote:
`ZT_TOKEN=########################`
what is ZT_TOKEN? How to get and how to use it?

Thanks in advance :)

**Comment by key-networks** [comment]
Firstly, you need to install zerotier-one - https://www.zerotier.com/download/

Then:
`sudo cat /var/lib/zerotier-one/authtoken.secret`

**Comment by Jarusss** [comment]
@key-networks I installed ZeroTier as described in installation instruction. But why and when should I use it?

**Comment by key-networks** [comment]
ztncui is a web UI to ZeroTier acting in the role of a network controller.  Without ZeroTier, ztncui has nothing to interact with.

**Comment by Jarusss** [comment]
Ok, i just try to understand it, because right now I haven't set this token and I'm able to add new nodes to my network and authorize. That is why I'm asking :-)

**Comment by Fastidious** [comment]
@Jarusss are you using `ztncui`? I went a little bit broader than the install instructions recommend. I granted access to `zerotier-one:zerotier-one` to the entire `zerotier-one` directory under `/var/lib/`. No issues.

**Comment by Jarusss** [comment]
@Fastidious I do not have any issues. I was wondering about this field. @key-networks wrote that ZT_TOKEN comes from authtoken.secret, but why need I use it? As I wrote, in my configuration I forgot (to be honest - do not know what it is) to add ZT_TOKEN to .env file and it is working. I can add new hosts, manage them, connect between them. That is why I was asking - where and why should I use authtoken.secret? 
Not as an issue - just wondering ;-)

**Comment by key-networks** [comment]
@Jarusss, did you perhaps execute the previous option?
```
sudo usermod -aG zerotier-one username
sudo chmod g+r /var/lib/zerotier-one/authtoken.secret
```

**Comment by Jarusss** [comment]
Yes. As I said - all steps from the instruction.

**Comment by key-networks** [comment]
Ok, that explains it - you need to do either A or B under step 3.  B is redundant if you have done A.
