### ISSUE TITLE
Create a public network

### ISSUE THREAD

**Issue by Fastidious** [key-networks/ztncui#5]
Is the ability to create a public network there, but I am missing it? Or is it something not available now, but planned for future enhancements? Thanks much!

**Comment by key-networks** [comment]
It's not available right now.  I'm just wondering about the use case if you can already do it via ZeroTier Central?  I would think that ztncui would be of more interest to people who want to set up secured networks that they can control.

**Comment by chotaire** [comment]
There is a clear use case for this. While zerotier-one already allows to orbit your own moons, it has been announced that it will soon also allow to create isolated planets without actually editing the source. This will allow fully autonomous zerotier-one networks whereas ztncui should be supporting such scenarios - ZeroTIer Central will as such not be used on a private ZeroTier infrastructure.

**Comment by chotaire** [comment]
Additionally, the already existing ability to create and orbit own moons does already allow a ZeroTier infrastructure to be run on a network without connectivity to planets. Moons and leafs will attempt to contact planets, but they will happily serve without.

**Comment by chotaire** [comment]
If you are interested in such a setup, please study https://www.zerotier.com/manual.shtml#4_4 ;)

**Comment by key-networks** [comment]
Fair enough.  I'm a bit swamped with work atm.  Will look at it when I have a chance.

**Comment by key-networks** [comment]
@Fastidious, this feature has been added under network detail.  Could you please test as follows and give me your feedback?

Please try this for RPM installation -

If it is a fresh installation:
sudo yum install https://download.key-networks.com/el7/ztncui/1/ztncui-release-1-1.noarch.rpm -y

For fresh installation or upgrade:
sudo yum --enablerepo=ztncui-testing install ztncui

Follow https://key-networks.com/ztncui/#installation if you need further details.

Let me know if you need a DEB package instead for testing.

**Comment by chotaire** [comment]
I found the option called "private" in network "detail". I was able to check / uncheck and the details were being updated.

**Comment by Fastidious** [comment]
Could I have a DEB package? Thanks!

**Comment by Fastidious** [comment]
Sorry, @key-networks, I am on finals, and had had no time to test. I got the package, hopefully will install it tomorrow. Thanks!

**Comment by key-networks** [comment]
@Fastidious, no problem - when you have time.

**Comment by sunfic** [comment]
I tested the DEB package with public network settings and it is working good.

**Comment by key-networks** [comment]
@sunfic - thanks for your feedback.
