### ISSUE TITLE
SSH Settings (Solution Not An Issue)

### ISSUE THREAD

**Issue by jimthedj65** [key-networks/ztncui#51]
Hi All,

just to let everyone know that I installed a fresh ztncui on ubuntu 18.04 bare metal server minimal install following the instructions at https://key-networks.com/ztncui/ after the install, I had some errors with tunnelling via ssh, one of the errors was **channel 2: open failed: administratively prohibited: open failed ztncui**

I solved this by changing my sshd_config file to 

AllowTcpForwarding yes
PermitOpen any
PermitTTY yes
PermitTunnel yes

after an ssh restart, I was able to open up the interface with 

ssh -p ssh_port -f username@ip_address_of_server -L 3333:localhost:3000 -N

then http://localhost:3333/ show the controller interface.

I am now successfully running heavy media feeds on using my own controller network setup, I hope someone finds this useful.

**Comment by key-networks** [comment]
Thanks for your feedback, @jimthedj65 !

**Comment by jimthedj65** [comment]
your welcome and thank you for the awesome interface
