### ISSUE TITLE
Building .deb packages

### ISSUE THREAD

**Issue by garakangas** [key-networks/ztncui#56]
Hi,

I'm trying to build .deb packages from the source code, I'm doing it mostly for learning it myself. I have encountered a bunch of problems, but I am curious, which OS are you using when you are building the .deb packages, and which builder are you using?

**Comment by key-networks** [comment]
Fedora and fpm.

**Comment by garakangas** [comment]
Okay, thank you, do you have any other special packages installed that you need to build the .deb packages?

**Comment by key-networks** [comment]
The build script https://github.com/key-networks/ztncui/blob/master/build/build.sh should show the dependencies.

**Comment by garakangas** [comment]
Okay, thank you for the answers, I will try and see if I have any success.
