### ISSUE TITLE
rename a member wont save after reboot server

### ISSUE THREAD

**Issue by ssteeltm** [key-networks/ztncui#59]
Hello! I've updated ztncui and in this new version when I do rename a member on network, it save new name ok, but if I restart my server, the name wont save the changes, it comes back to old name.

Maybe I'm missing something? thank you!

**Comment by ssteeltm** [comment]
I forgot to tell that I used the debian package to install ztncui.

**Comment by key-networks** [comment]
@ssteeltm Could you please let us know what Linux distribution you are using?  Which version of ztncui have you now installed and which version were you previously using?

**Comment by ssteeltm** [comment]
Sorry about that, heres the info:
I was using the docker image, then I created a new debian install in new server, made install with .deb package, then I copied from old docker install:

/opt/key-networks/ztncui/etc
/var/lib/zerotier-one

Everithing is working ok but this thing on rename wont save after reboot.

**Comment by ssteeltm** [comment]
Solved!
It was permission on /opt/key-networks/ztncui/etc/storage
It wasnt getting updated, so I changed from 755 to 775 and began to work!

Thank you and Thank you again for this great tool!

**Comment by MANKUD** [comment]
> /opt/key-networks/ztncui/etc/storage

@ssteeltm Thanks a lot I also had the same issue fixed it by changing permissions.
