### ISSUE TITLE
Updating zerotier-one in ztncui docker image will drop JSON errors when showing members

### ISSUE THREAD

**Issue by chotaire** [key-networks/ztncui#6]
When updating zerotier-one to version 1.2.8 (yum update) and restarting the ztncui docker container, the following error message will show within ztncui when clicking on members:

`Error resolving detail for network 12345: ParseError: Unexpected token a in JSON at position 3 in "http://localhost:9993/controller/network/12345/member"`

The problem persists when creating new networks, not only with already existing networks.

**Comment by whitegerry** [comment]
Same issue with version 1.2.8.

**Comment by key-networks** [comment]
This appears to be a bug in zerotier-one v1.2.8: https://github.com/zerotier/ZeroTierOne/pull/746
Until this bug is fixed, don't upgrade zerotier-one.

**Comment by chotaire** [comment]
Thanks. Waiting for the zerotier-one merge of michaelansel:patch-1.
