### ISSUE TITLE
Link not going anywhere

### ISSUE THREAD

**Issue by garakangas** [key-networks/ztncui#61]
From the page for one of my networks I clicked on one of the properties (rules in this case, but authTokens also work) under "Detail for network", this sent me to a page saying "Editing of (property) has not been implemented. Note that you may be able to edit some properties on the Members page." The word "Member" is a link going to https://hostname:port/controller/network/networkID/members, this link however does not go anywhere since the members-page was removed in the latest version of ZTNCUI.

**Comment by key-networks** [comment]
This issue has been resolved by @lideming and ztncui 0.7.1 has been built and is available - instructions for installation are at https://key-networks.com/ztncui .
