### ISSUE TITLE
Cannot delete non-existent route target

### ISSUE THREAD

**Issue by InPRTx** [key-networks/ztncui#74]
If you try to delete the ipv6 route in the route page,the will say 
```Error deleting route for network c4cd354c25f21cdb: Error: Cannot delete non-existent route target```
https://github.com/key-networks/ztncui/blob/d966c51e38f98ade21d1e1de3ff5013e05285898/src/controllers/zt.js#L201
This curl request is like:
```
curl 'http://xxxx:36236/controller/network/c4cd354c25f21cdb/routes/dfdf:afcd:c125:514a::/56/delete' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H 'Accept-Language: zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2' --compressed -H 'Connection: keep-alive' -H 'Referer: http://xxxx:36236/controller/network/c4cd354c25f21cdb/routes' -H 'Cookie: ***' -H 'Upgrade-Insecure-Requests: 1'

**Comment by key-networks** [comment]
@InPRTx please test as per https://github.com/key-networks/ztncui/pull/75 and let us know if this has resolved the issue?

**Comment by InPRTx** [comment]
> @InPRTx please test as per #75 and let us know if this has resolved the issue?

yes it works
