### ISSUE TITLE
能否出vue语言文件 我想汉化需要修改源码

### ISSUE THREAD

**Issue by chenxudong2020** [key-networks/ztncui#77]
如题目写的

**Comment by lideming** [comment]
Translation of the title: Could you make "vue language file"? I want to translate this project into Chinese and need to modify the source code.

I don't know what did you mean by "vue language file". Vue is not used in this project. The web pages are rendered from pug templates on the server.
不知道你说的 "vue 语言文件" 是什么，这个项目没有用到 Vue，网页是在服务端从 pug 模板渲染出来的。

If you want to make a "Chinese version", try modify text in pug templates under `src/views`, though I think a better way is to add real i18n support in this project.
如果你想汉化这个项目，可以尝试修改 `src/views` 里面 pug 模板的文本，得到一个“汉化版”，虽然我认为更好的办法是给这个项目增加真正的多语言支持。

**Comment by chenxudong2020** [comment]
不好意思看起来结构像vue, 我想表达的意思是1.项目能否提供国际化支持 单独语言文件 2.我找了安装rpm之后的文件想直接改文件汉化没找到3.页面太丑了4.能否在members的ip，光标移动到ip上面提供弹出复制 每次想ping还要复制可以参考下tailscale

**Comment by lideming** [comment]
项目作者失踪至少一个月了，不像是有时间大改。
RPM 安装的源码都被打包到一个文件里了，你需要参考 readme 的 [Installing](https://github.com/key-networks/ztncui#installing) 部分从源码运行。

**Comment by chenxudong2020** [comment]
从源码构建都没成功过啊 。。。。 你不是源码作者吗 或者告诉我怎么打包成rpm 这太难了。。。。 真服了这个作者死哪去了

**Comment by kmahyyg** [comment]
> 从源码构建都没成功过啊 。。。。 你不是源码作者吗 或者告诉我怎么打包成rpm 这太难了。。。。 真服了这个作者死哪去了

这是开源项目，你没有付钱。没有权利用粗俗的语言要求维护者做什么。

**Comment by chenxudong2020** [comment]
自己编译成功了 gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  CC(target) Release/obj.target/libargon2/argon2/src/opt.o
  CC(target) Release/obj.target/libargon2/argon2/src/argon2.o
  CC(target) Release/obj.target/libargon2/argon2/src/core.o
  CC(target) Release/obj.target/libargon2/argon2/src/blake2/blake2b.o
  CC(target) Release/obj.target/libargon2/argon2/src/thread.o
  CC(target) Release/obj.target/libargon2/argon2/src/encoding.o
  AR(target) Release/obj.target/argon2.a
  COPY Release/argon2.a
  CXX(target) Release/obj.target/argon2/src/argon2_node.o
  SOLINK_MODULE(target) Release/obj.target/argon2.node
  COPY Release/argon2.node
make: Leaving directory '/root/ztncui/src/node_modules/argon2/build'
gyp info ok 
~/ztncui/src ~/ztncui/build
> pkg@5.5.1
~/ztncui/build
Created package {:path=>"/root/ztncui/Release/ztncui-0.8.4-1.x86_64.rpm"}
Adding action files
Created package {:path=>"/root/ztncui/Release/ztncui_0.8.4_amd64.deb"}

已经汉化完成 非常OK 有点麻烦

**Comment by chenxudong2020** [comment]
ztncui中文版已经开源 包含编译好的rpm和deb安装包 https://gitee.com/opopop880/ztncui

**Comment by chenxudong2020** [comment]
> 项目作者失踪至少一个月了，不像是有时间大改。 RPM 安装的源码都被打包到一个文件里了，你需要参考 readme 的 [Installing](https://github.com/key-networks/ztncui#installing) 部分从源码运行。

已经自己编译好了中文版并且开源了 https://gitee.com/opopop880/ztncui   png的语法不熟悉 vue还知道点 不过一个个改png改挺麻烦的额

**Comment by chenxudong2020** [comment]
> > 从源码构建都没成功过啊 。。。。 你不是源码作者吗 或者告诉我怎么打包成rpm 这太难了。。。。 真服了这个作者死哪去了
> 
> 这是开源项目，你没有付钱。没有权利用粗俗的语言要求维护者做什么。如果你想打包，可以参考 Docker 的运行方式打包。但是，由于目标环境系统和NodeJS的差异，可能会比较困难。
https://gitee.com/opopop880/ztncui

**Comment by chenxudong2020** [comment]
![1641134301(1)](https://user-images.githubusercontent.com/61214170/147879362-0727f0f4-ded6-4ba7-82f7-0a96ba4ad6fe.png)

**Comment by key-networks** [comment]
@chenxudong2020 - well done on making the Chinese translation!

**Comment by ali-95** [comment]
как сделать чтобы можно было переводить на другие языки?
--------------------------------------------------------------
how to make it possible to translate into other languages?

**Comment by key-networks** [comment]
@ali-95 you can edit the views/*.pug files.

**Comment by ali-95** [comment]
Мне нужно скопировать ваш репозиторий, а потом переводить?
Я думал что есть переменные которые можно привести, если нет то оставим так.
______________________________________________________________________________
Do I need to copy your repository and then translate?
I thought that there are variables that can be brought, if not, then we'll leave it like this.

**Comment by key-networks** [comment]
Yes, you would need to copy the repository.
