### ISSUE TITLE
Unable to assign IP for member without name

### ISSUE THREAD

**Issue by chotaire** [key-networks/ztncui#8]
When a new member (or previously deleted member) joins a network and has not yet been given a "Member name", clicking on IP assignment will drop the following error:

`Error resolving detail for member 123 of network 12345: TypeError: Assignment to constant variable.`

Workaround: Give a member name then try again.

**Comment by key-networks** [comment]
This bug is now fixed in the source (let me know if it performs as expected), but I'm having issues building the rpm and deb packages.  If you can check against source in the meantime, that would be great.  Otherwise the packages will hopefully be updated one of these days.

**Comment by chotaire** [comment]
Hm, it appears the webserver and UI code inside the _keynetworks/ztncui_ docker image has been compiled into one blob (why?). 

```
[root@9e7b68d92eee /]# find / -name "*.js"
[root@9e7b68d92eee /]#
[root@9e7b68d92eee /]# ls -al /opt/key-networks/ztncui/ztncui
-rwxr-xr-x. 1 ztncui ztncui 48503316 Feb  5 07:31 /opt/key-networks/ztncui/ztncui
[root@9e7b68d92eee /]# file /opt/key-networks/ztncui/ztncui
/opt/key-networks/ztncui/ztncui: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.18, BuildID[sha1]=b25d601cd11db4b069708be88c4a269c44c29ec9, not stripped
```
So I apologize I do not have a test environment ready at the moment. Please be so kind to provide a RPM and I will be happy to test.

**Comment by key-networks** [comment]
Please try this -

If it is a fresh installation:
sudo yum install https://download.key-networks.com/el7/ztncui/1/ztncui-release-1-1.noarch.rpm -y

For fresh installation or upgrade:
sudo yum --enablerepo=ztncui-testing install ztncui

Follow https://key-networks.com/ztncui/#installation if you need further details.

**Comment by key-networks** [comment]
@chotaire please let me know if this has resolved the issue. Thanks.

**Comment by chotaire** [comment]
I can confirm this issue is fixed.
