### ISSUE TITLE
centos8 构建ztncui rpm包出现问题

### ISSUE THREAD

**Issue by chenxudong2020** [key-networks/ztncui#81]
当我运行build里面的脚本 build.sh时候的 命令
pkg -c ./package.json -t node16-linux-x64 bin/www -o $BUILD_DIR/ztncui

centos中没有pkg命令 查阅资料是pkg是freebsd下面的包管理命令 是否此软件ztncui只能在freebsd下打包成功？
![image](https://user-images.githubusercontent.com/61214170/147846826-c3550206-eacd-4273-afbd-536751367732.png)

**Comment by lideming** [comment]
The "pkg" is this one: https://github.com/vercel/pkg

**Comment by chenxudong2020** [comment]
![image](https://user-images.githubusercontent.com/61214170/147854652-5bc5006b-a25b-459e-9f7b-a107b5f1c7dc.png)  node v16.0.0
![image](https://user-images.githubusercontent.com/61214170/147854686-191769f9-5cd3-4607-8a13-79424c9a1dc9.png)
npm 版本7.10.0
最后编译还是报错 看起来是项目升级v16.0.0 但是有些库没有升级上来导致依赖冲突 不知道怎么解决了

**Comment by chenxudong2020** [comment]
(![image](https://user-images.githubusercontent.com/61214170/147869530-ce476af0-2958-4494-83e9-f44872e5a191.png))

**Comment by chenxudong2020** [comment]
已经编译成功！！！！！！！！！！！！

**Comment by chenxudong2020** [comment]
![1641134301(1)](https://user-images.githubusercontent.com/61214170/147879304-e310846b-5ae9-49b4-b859-1f633bb7568f.png)
已经开源
https://gitee.com/opopop880/ztncui
