### ISSUE TITLE
New Clients running v1.6.2 do not appear on Zerotier dashboard running version 1.6.5 (Clients running 1.8.3 WORK!)

### ISSUE THREAD

**Issue by amendolaro** [key-networks/ztncui#85]
Running ZeroTier version 1.6.5 and have over 1400 clients without issue. Today 2/9/22 i am no longer able to see new clients come online running 1.6.2. I tested this with multiple units. I then use 1.8.3 and they appear immediately. Could this be an issue with zeroteir servers?

**Comment by key-networks** [comment]
Same as per https://github.com/key-networks/ztncui-containerized/issues/28
