### ISSUE TITLE
Members always shows as offline in peer status

### ISSUE THREAD

**Issue by ThierryBegin** [key-networks/ztncui#90]
Members always shows as offline in the peer status section of the members area

**Comment by lideming** [comment]
Could you run `sudo zerotier-cli peers` on your controller server, and check status of members in the output?

**Comment by ThierryBegin** [comment]
![image](https://user-images.githubusercontent.com/2735823/165188765-517f0fb7-6727-40a5-ad9f-73da361687b5.png)

**Comment by guideloom** [comment]
This is probably a duplicate of https://github.com/key-networks/ztncui/issues/69
This could be due to the nodes being "relayed" and not directly reachable.

**Comment by ThierryBegin** [comment]
Yes I think it's related. ill close that one
